import type { Scenario } from '../types'
import { base, O, D } from './formations'

/**
 * LEVEL 6 — "Full Speed": the final exam. ALL 9 calls in play
 * (BALL, HOLD, CHECK, HOT, TWO, SLIDE, FIRE, CUTTER, TOPSIDE).
 * No tutorials. Real game possessions: longer 3-5 action chains,
 * faster reads. Player controls D1 guarding A1 in all 15.
 * Some possessions accept more than one correct call.
 */
export const level6: Scenario[] = [
  {
    id: 'L6-1',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.M1,
    actions: [
      { type: 'pass', playerIndex: O.M1, toPlayerIndex: O.M2, delay: 200, duration: 600 },
      { type: 'catch', playerIndex: O.M2, delay: 800, duration: 100 },
      { type: 'pass', playerIndex: O.M2, toPlayerIndex: O.A1, delay: 1000, duration: 700 },
      { type: 'catch', playerIndex: O.A1, delay: 1700, duration: 100 },
    ],
    correctCalls: ['BALL'],
    callOpensAt: 1900,
    setupHint: 'Ball working around the perimeter toward your man.',
    explanation: 'After the swing your man catches it squared to the goal. The call is BALL!',
  },
  {
    id: 'L6-2',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.A2,
    actions: [
      { type: 'pass', playerIndex: O.A2, toPlayerIndex: O.A3, delay: 200, duration: 700 },
      { type: 'catch', playerIndex: O.A3, delay: 900, duration: 100 },
      { type: 'pass', playerIndex: O.A3, toPlayerIndex: O.M2, delay: 1100, duration: 700 },
      { type: 'catch', playerIndex: O.M2, delay: 1800, duration: 100 },
    ],
    correctCalls: ['HOT'],
    callOpensAt: 2000,
    setupHint: 'Ball swung up and over to the middle.',
    explanation: 'The ball settled one pass from your man and you are the next slide. The call is HOT!',
  },
  {
    id: 'L6-3',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.A1,
    actions: [
      { type: 'move', playerIndex: O.A1, team: 'offense', target: { x: 14, y: 96 }, delay: 200, duration: 800 },
      { type: 'move', playerIndex: O.A1, team: 'offense', target: { x: 12, y: 102 }, delay: 1000, duration: 700 },
    ],
    correctCalls: ['HOLD'],
    callOpensAt: 1300,
    setupHint: 'Your man has it but is backing it out behind.',
    explanation: 'Your man is carrying the ball away from the goal — not a threat. The call is HOLD!',
  },
  {
    id: 'L6-4',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.M3,
    actions: [
      { type: 'pass', playerIndex: O.M3, toPlayerIndex: O.M2, delay: 200, duration: 600 },
      { type: 'catch', playerIndex: O.M2, delay: 800, duration: 100 },
      { type: 'pass', playerIndex: O.M2, toPlayerIndex: O.A2, delay: 1000, duration: 900 },
    ],
    correctCalls: ['CHECK'],
    callOpensAt: 1400,
    setupHint: 'Ball moving fast around the horn.',
    explanation: 'The ball is in the air on the feed to X. The call is CHECK!',
  },
  {
    id: 'L6-5',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.M1,
    actions: [
      { type: 'pass', playerIndex: O.M1, toPlayerIndex: O.M2, delay: 200, duration: 600 },
      { type: 'catch', playerIndex: O.M2, delay: 800, duration: 100 },
      { type: 'pass', playerIndex: O.M2, toPlayerIndex: O.M3, delay: 1000, duration: 600 },
      { type: 'catch', playerIndex: O.M3, delay: 1600, duration: 100 },
      { type: 'dodge', playerIndex: O.M3, team: 'offense', target: { x: 60, y: 70 }, delay: 1750, duration: 1100 },
    ],
    correctCalls: ['TOPSIDE'],
    callOpensAt: 2100,
    setupHint: 'Ball reversed to the top-side middie who is winding up.',
    explanation: 'A teammate up top has the ball and is driving — force him topside. The call is TOPSIDE!',
  },
  {
    id: 'L6-6',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.M2,
    actions: [
      { type: 'pass', playerIndex: O.M2, toPlayerIndex: O.A3, delay: 200, duration: 800 },
      { type: 'catch', playerIndex: O.A3, delay: 1000, duration: 100 },
      { type: 'dodge', playerIndex: O.A3, team: 'offense', target: { x: 64, y: 98 }, delay: 1150, duration: 1100 },
      { type: 'move', playerIndex: D.D3, team: 'defense', target: { x: 70, y: 90 }, delay: 1500, duration: 900 },
    ],
    correctCalls: ['SLIDE'],
    callOpensAt: 2000,
    setupHint: 'Far-side attacker catches and goes hard to the cage.',
    explanation: 'A3 beat his man dodging to the goal and help must come. The call is SLIDE!',
  },
  {
    id: 'L6-7',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.M2,
    actions: [
      { type: 'pass', playerIndex: O.M2, toPlayerIndex: O.M1, delay: 200, duration: 600 },
      { type: 'catch', playerIndex: O.M1, delay: 800, duration: 100 },
      { type: 'pass', playerIndex: O.M1, toPlayerIndex: O.A1, delay: 1000, duration: 700 },
      { type: 'catch', playerIndex: O.A1, delay: 1700, duration: 100 },
      { type: 'dodge', playerIndex: O.A1, team: 'offense', target: { x: 38, y: 96 }, delay: 1850, duration: 1100 },
      { type: 'move', playerIndex: D.D1, team: 'defense', target: { x: 42, y: 90 }, delay: 2200, duration: 800 },
    ],
    correctCalls: ['FIRE'],
    callOpensAt: 2400,
    setupHint: 'Ball comes to your man and he attacks you immediately.',
    explanation: 'Your man caught it and dodged past you to the cage. The call is FIRE!',
  },
  {
    id: 'L6-8',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.A1,
    actions: [
      { type: 'pass', playerIndex: O.A1, toPlayerIndex: O.A2, delay: 200, duration: 700 },
      { type: 'catch', playerIndex: O.A2, delay: 900, duration: 100 },
      { type: 'pass', playerIndex: O.A2, toPlayerIndex: O.M2, delay: 1100, duration: 800 },
      { type: 'catch', playerIndex: O.M2, delay: 1900, duration: 100 },
      { type: 'cut', playerIndex: O.A3, team: 'offense', target: { x: 48, y: 98 }, delay: 2000, duration: 900 },
    ],
    correctCalls: ['CUTTER'],
    callOpensAt: 2300,
    setupHint: 'Ball up top — watch the off-ball attackers.',
    explanation: 'A3 is cutting through the crease as the ball is up top. The call is CUTTER!',
  },
  {
    id: 'L6-9',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.M3,
    actions: [
      { type: 'pass', playerIndex: O.M3, toPlayerIndex: O.A3, delay: 200, duration: 700 },
      { type: 'catch', playerIndex: O.A3, delay: 900, duration: 100 },
      { type: 'pass', playerIndex: O.A3, toPlayerIndex: O.A2, delay: 1100, duration: 800 },
      { type: 'catch', playerIndex: O.A2, delay: 1900, duration: 100 },
    ],
    correctCalls: ['TWO'],
    callOpensAt: 2100,
    setupHint: 'Ball worked all the way to X behind.',
    explanation: 'The ball settled two passes from your man on the help side. The call is TWO!',
  },
  {
    id: 'L6-10',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.A2,
    actions: [
      { type: 'pass', playerIndex: O.A2, toPlayerIndex: O.M1, delay: 200, duration: 800 },
      { type: 'catch', playerIndex: O.M1, delay: 1000, duration: 100 },
      { type: 'pass', playerIndex: O.M1, toPlayerIndex: O.A1, delay: 1200, duration: 700 },
      { type: 'catch', playerIndex: O.A1, delay: 1900, duration: 100 },
    ],
    correctCalls: ['BALL'],
    callOpensAt: 2100,
    setupHint: 'Ball circulating then back down to your man.',
    explanation: 'Your man received the ball facing the cage — a live threat. The call is BALL!',
  },
  {
    id: 'L6-11',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.M1,
    actions: [
      { type: 'pass', playerIndex: O.M1, toPlayerIndex: O.M2, delay: 200, duration: 600 },
      { type: 'catch', playerIndex: O.M2, delay: 800, duration: 100 },
      { type: 'pass', playerIndex: O.M2, toPlayerIndex: O.A2, delay: 1000, duration: 800 },
      { type: 'catch', playerIndex: O.A2, delay: 1800, duration: 100 },
    ],
    correctCalls: ['TWO', 'HOT'],
    callOpensAt: 2000,
    setupHint: 'Ball swung over the top and down to X.',
    explanation: 'The ball is well away from your man on the help side, adjacent enough some defenses bump it. The call is TWO!',
  },
  {
    id: 'L6-12',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.A3,
    actions: [
      { type: 'pass', playerIndex: O.A3, toPlayerIndex: O.M3, delay: 200, duration: 700 },
      { type: 'catch', playerIndex: O.M3, delay: 900, duration: 100 },
      { type: 'pass', playerIndex: O.M3, toPlayerIndex: O.M1, delay: 1100, duration: 800 },
      { type: 'catch', playerIndex: O.M1, delay: 1900, duration: 100 },
    ],
    correctCalls: ['HOT', 'TWO'],
    callOpensAt: 2100,
    setupHint: 'Ball reversed up top to the wing by your man.',
    explanation: 'The ball is one pass from your man and you are the closest slide. The call is HOT!',
  },
  {
    id: 'L6-13',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.M2,
    actions: [
      { type: 'pass', playerIndex: O.M2, toPlayerIndex: O.M3, delay: 200, duration: 600 },
      { type: 'catch', playerIndex: O.M3, delay: 800, duration: 100 },
      { type: 'pass', playerIndex: O.M3, toPlayerIndex: O.A3, delay: 1000, duration: 700 },
      { type: 'catch', playerIndex: O.A3, delay: 1700, duration: 100 },
      { type: 'cut', playerIndex: O.A1, team: 'offense', target: { x: 48, y: 98 }, delay: 1850, duration: 900 },
    ],
    correctCalls: ['CUTTER', 'BALL'],
    callOpensAt: 2100,
    setupHint: 'Ball to the far side as your man cuts to the crease.',
    explanation: 'Your man is cutting hard through the crease looking for the feed. The call is CUTTER!',
  },
  {
    id: 'L6-14',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.M2,
    actions: [
      { type: 'pass', playerIndex: O.M2, toPlayerIndex: O.M1, delay: 200, duration: 600 },
      { type: 'catch', playerIndex: O.M1, delay: 800, duration: 100 },
      { type: 'pass', playerIndex: O.M1, toPlayerIndex: O.A2, delay: 1000, duration: 800 },
      { type: 'catch', playerIndex: O.A2, delay: 1800, duration: 100 },
      { type: 'dodge', playerIndex: O.A2, team: 'offense', target: { x: 50, y: 102 }, delay: 1950, duration: 1100 },
      { type: 'move', playerIndex: D.D2, team: 'defense', target: { x: 52, y: 100 }, delay: 2300, duration: 900 },
    ],
    correctCalls: ['SLIDE'],
    callOpensAt: 2500,
    setupHint: 'Ball gets to X and he dodges from behind.',
    explanation: 'A2 beat his defender on the dodge from X and needs a slide. The call is SLIDE!',
  },
  {
    id: 'L6-15',
    level: 6,
    initialPositions: base(),
    playerDefenderIndex: D.D1,
    guardedAttackerIndex: O.A1,
    ballStartIndex: O.A3,
    actions: [
      { type: 'pass', playerIndex: O.A3, toPlayerIndex: O.M2, delay: 200, duration: 700 },
      { type: 'catch', playerIndex: O.M2, delay: 900, duration: 100 },
      { type: 'pass', playerIndex: O.M2, toPlayerIndex: O.M1, delay: 1100, duration: 600 },
      { type: 'catch', playerIndex: O.M1, delay: 1700, duration: 100 },
      { type: 'dodge', playerIndex: O.M1, team: 'offense', target: { x: 34, y: 70 }, delay: 1850, duration: 1100 },
    ],
    correctCalls: ['TOPSIDE'],
    callOpensAt: 2200,
    setupHint: 'Ball reversed up top and the middie squares to drive.',
    explanation: 'A teammate up top has the ball and is dodging — direct him topside away from the middle. The call is TOPSIDE!',
  },
]
